# -*- coding: utf-8 -*-
"""task1_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eF3G1AUhkAh-AWOd09E5K71j7zFar0iR
"""

data = read_csv("Trails.csv")


Status_Active_or_not = data['STATUS'].tolist()
status_count=0
for item in Status_Active_or_not:
  if item=='ACTIVE':
    status_count=status_count+1
print(status_count) 

Lighting_or_not = data['LIGHT'].tolist()
light_count=0
for item in Lighting_or_not:
  if item=='Yes':
    light_count=light_count+1
print(light_count)