# -*- coding: utf-8 -*-
"""task1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vWhI7r7o0Aa8CAZj5fpXLfvxWYlTYnbH
"""

import csv
import inspect
from platform import system as system_name
from subprocess import run, PIPE
from concurrent.futures import ThreadPoolExecutor
import re


stdout_incorrect_warning = """
The message is different from the one specified in the task.
Should be: {}
And output: {}
"""


def check_attr_or_method(obj, attr=None, method=None):
    if attr:
        assert getattr(obj, attr, None) != None, "Variable not found"
        assert not inspect.ismethod(
            getattr(obj, attr)
        ), f"{attr} must be a variable, not a method"
    if method:
        assert getattr(obj, method, None) != None, "Method not found"
        assert inspect.ismethod(
            getattr(obj, method)
        ), f"{method} must be a method, not a variable"