# -*- coding: utf-8 -*-
"""task1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13h2jkNrvKOoZNZLiXM5bstDa8fqKzbKx
"""

data = read_csv("Trails.csv")


Inst_year = data['INST_YEAR'].tolist()
count=0
for item in Inst_year:
  if item>2000:
    count=count+1
print(count)